### PR TITLE
layout & setup update

### PR DESCRIPTION
**Pull request by btemperli**
two relevant changes:

1.  I added some informations about the setup on a Mac, including the new setup of bundler.
2. I added some space to the subtitles to clean up the layout a bit.

(sorry to combine these two in one pull request, but the first one is more a github-improvement and not relevant to the cevi.tools-website.)

### CODE REVIEW

**Review by wp99cp — APPROVED** [review]
Seems fine!

Sidenote: we are currently trying out another static builder ([vitepress](https://vitepress.vuejs.org/), on the branch https://github.com/cevi/Cevi-Tools-Webpage/tree/feature_newDesign) which will improve the layout further...

**Comment by wp99cp** [comment]
**Another side note:** the build pipeline (checks) failed since you are pushing from your local project fork. For security reasons in such a case, GitHub Action cannot access the secrets used to publish the preview build. See Secrets are not passed to workflows that are triggered by a pull request from a fork. [Learn more about encrypted secrets](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

**Comment by wp99cp** [comment]
> **Another side note:** the build pipeline (checks) failed since you are pushing from your local project fork. For security reasons in such a case, GitHub Action cannot access the secrets used to publish the preview build. See Secrets are not passed to workflows that are triggered by a pull request from a fork. [Learn more about encrypted secrets](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

I've merged our PR into the dev branch and created a new PR #38 to release your changes, as preview builds are mandatory for pushing to main.

**Comment by btemperli** [comment]
> **Another side note:** the build pipeline (checks) failed since you are pushing from your local project fork. For security reasons in such a case, GitHub Action cannot access the secrets used to publish the preview build. See Secrets are not passed to workflows that are triggered by a pull request from a fork. [Learn more about encrypted secrets](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

Good to know! I didn't want to create a feature-branch only for these 2 small changes, so I went the fork-way. `dev`-branch would be a good (or probably better 😄) option. Next time...

**Pull request merged**
