### PR TITLE
Recplace default theme with minimal theme

### PR DESCRIPTION
**Pull request by wp99cp**
Create the basics for a custom theme based on the minimal theme.

Todo:
- [ ] Check if auto-deployment works
- [ ] Add meaningful content
- [ ] Point [cevi.tools](cevi.tools) to githubpage

### CODE REVIEW

**Comment by wp99cp** [comment]
@btemperli I think my access rights on this repo is not enough to change deployment settings. Can you give me the same rights on this repo as for the https://github.com/cevi/automatic_walk-time_tables repo?

**Review by btemperli — APPROVED** [review]
looks good.

**Comment by btemperli** [comment]
@wp99cp you should have access now.

**Comment by wp99cp** [comment]
This was a bit to fast, I think the auto-deployment didn't work

**Pull request merged**
