### PR TITLE
Add News Entry: Update QR Code Generator

### PR DESCRIPTION
**Pull request by wp99cp**

### CODE REVIEW

**Comment by wp99cp** [comment]
@maede97, there is no Link to the news entry on the landing page. What did I do wrong?

**Comment by wp99cp** [comment]
> @maede97, there is no Link to the news entry on the landing page. What did I do wrong?

Never mind, it was a time-zone issue...

**Comment by ThomasHaefliger** [comment]
Text beneath "Telefonnummern" and "WLAN-Zugriffsdaten" are the same! Copy Paste error?

**Comment by wp99cp** [comment]
> Text beneath "Telefonnummern" and "WLAN-Zugriffsdaten" are the same! Copy Paste error?

Thank's! I've updated the text.

**Comment by wp99cp** [comment]
@ThomasHaefliger can you check again and then approve, such that we can publish the text?

**Review by ThomasHaefliger — APPROVED** [review]

**Pull request merged**
